CREATE TABLE Matches
(
    ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Player1 INTEGER NOT NULL,
    Player2 INTEGER NOT NULL,
    Winner  INTEGER NOT NULL,
    FOREIGN KEY (Player1) REFERENCES Players (ID),
    FOREIGN KEY (Player2) REFERENCES Players (ID),
    FOREIGN KEY (Winner)  REFERENCES Players (ID)
);